set -e

# Guard against the make-clean-build-target race (issue #83). A single `make`
# invocation with both `clean` and a build goal lets -j run them concurrently,
# and clean ends up rm-ing .o files mid-archive.
if grep -nE '\bmake\b[^\n]*\bclean\b[^\n]*(\blib[A-Za-z0-9_]+\.a\b|\ball\b)' CMakeLists.txt; then
    echo "ERROR: BUILD_COMMAND has 'make ... clean <target>' on one line (race per #83)." >&2
    echo "Split into two sequential COMMAND steps." >&2
    exit 1
fi

# mmvec compiles its objective once per instruction set and picks at load time, so
# a fit's result depends on the CPU running it -- the same property scikit-bio has
# through OpenBLAS, and an accepted one. Expected values in the SQL tests are
# carved against the BASELINE kernel, so pin it here: without this the suite would
# assert different numbers on an AVX-512 CI runner than on an AVX2 one, and a real
# regression would be indistinguishable from a change of machine.
#
# The wide variants are not left untested by this. test/cpp/test_MMvec.cpp calls
# each one directly -- no environment variable involved, since DetectIsa() memoizes
# and one process can only ever observe one dispatch decision -- and checks them
# against baseline within the carved kIsa*Tol bands.
#
# Honours an externally-set value so `MIINT_SIMD=avx512 bash run_tests.sh` still
# works for a deliberate cross-check.
export MIINT_SIMD="${MIINT_SIMD:-baseline}"
echo "MIINT_SIMD=$MIINT_SIMD (mmvec kernel; expected values are carved against 'baseline')"

# Start local HTTP server for HTTPS reader tests (unless already set externally)
HTTP_SERVER_PID=""
if [ -z "$MIINT_HTTPS_TEST_URL" ]; then
    # Find a free port: bind to port 0, read assigned port, close immediately
    HTTPS_TEST_PORT=$(python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()")
    python3 -m http.server "$HTTPS_TEST_PORT" --directory data/ > /dev/null 2>&1 &
    HTTP_SERVER_PID=$!
    trap "kill $HTTP_SERVER_PID 2>/dev/null || true" EXIT

    # Wait for server to be ready (up to 3 seconds)
    HTTP_SERVER_READY=0
    for i in $(seq 1 15); do
        if curl -s "http://localhost:$HTTPS_TEST_PORT/" > /dev/null 2>&1; then
            HTTP_SERVER_READY=1
            break
        fi
        sleep 0.2
    done

    if [ "$HTTP_SERVER_READY" -ne 1 ]; then
        echo "ERROR: HTTP test server failed to start on port $HTTPS_TEST_PORT"
        exit 1
    fi

    export MIINT_HTTPS_TEST_URL="http://localhost:$HTTPS_TEST_PORT"
fi

# Detect optional external tools
if command -v ascp &> /dev/null; then
    export ASPERA_AVAILABLE=1
fi

# gpl-boundary daemon (process-isolation host for GPL tools incl. fasttree).
# When present we exercise the full phylogeny_fasttree round trip; when not,
# parity tests skip gracefully.
if command -v gpl-boundary &> /dev/null; then
    export GPL_BOUNDARY_AVAILABLE=1
fi

# Independent native FastTree binary (bioconda or built from source) used as
# the parity oracle for phylogeny_fasttree. Distinct from gpl-boundary's
# vendored ext/fasttree library.
if command -v FastTree &> /dev/null; then
    export FASTTREE_AVAILABLE=1
fi

# Phase 6: phylogeny_fasttree parity oracles.
#
# data/fasttree/{tiny,moderate}.fa are committed input fixtures; their
# *.golden.nwk siblings are the bioconda FastTree binary's outputs for those
# fixtures with -seed 42 -nosupport (regenerated by setting
# MIINT_FASTTREE_REGENERATE=1 below). Two sidecars per fixture pin freshness:
#   *.golden.fixture.sha       — sha256 of the input fixture (catches edits to
#                                the fasta without an oracle refresh)
#   *.golden.fasttree.version  — `FastTree | grep Version` of the binary that
#                                generated the oracle (warns when the
#                                installed FastTree differs — a different
#                                bioconda version can produce different
#                                topologies/branch lengths even with the same
#                                seed)
#
# Each fixture exports an independent gate (MIINT_FASTTREE_TINY_PARITY_OK,
# MIINT_FASTTREE_MODERATE_PARITY_OK). The parity test require-envs both, so a
# single stale fixture skips the whole file rather than silently letting the
# other fixture mask the divergence.
#
# To regenerate: rm data/fasttree/*.golden.{nwk,fixture.sha,fasttree.version}
# and rerun run_tests.sh with MIINT_FASTTREE_REGENERATE=1.
ft_get_version() {
    # FastTree writes its banner to stderr ("FastTree Version 2.2.0 ..."). The
    # 2>&1 fold + first-line grep is enough; if FastTree isn't on PATH the
    # grep returns empty and the caller can detect the empty string.
    FastTree 2>&1 < /dev/null | head -1 | grep -oE 'Version [0-9][0-9.]*' | head -1
}

ft_regenerate_one() {
    # Args: fixture, golden, sha_file, version_file
    # Captures FastTree stderr to a sibling .regen.log on failure so the
    # diagnostic survives — /dev/null was throwing it away.
    local fixture="$1"
    local golden="$2"
    local sha_file="$3"
    local version_file="$4"
    if [ "${MIINT_FASTTREE_REGENERATE:-0}" != "1" ]; then
        return 0
    fi
    if [ -z "${FASTTREE_AVAILABLE:-}" ]; then
        echo "Warning: MIINT_FASTTREE_REGENERATE=1 but FastTree not on PATH; oracles not refreshed"
        return 0
    fi
    if [ ! -f "$fixture" ]; then
        echo "Warning: fixture $fixture missing; cannot regenerate oracle"
        return 0
    fi
    local logfile="${golden%.nwk}.regen.log"
    echo "Regenerating FastTree parity oracle from $fixture..."
    if FastTree -nt -seed 42 -nosupport "$fixture" > "$golden" 2> "$logfile"; then
        sha256sum "$fixture" | awk '{print $1}' > "$sha_file"
        local v
        v=$(ft_get_version)
        if [ -n "$v" ]; then
            echo "$v" > "$version_file"
        fi
        rm -f "$logfile"
        echo "FastTree oracle regenerated at $golden ($v)"
    else
        rm -f "$golden"
        echo "Warning: FastTree oracle regeneration failed for $fixture; diagnostic at $logfile"
    fi
}

ft_check_one() {
    # Args: fixture, golden, sha_file, version_file
    # Echoes exactly one of "FRESH" or "STALE: <reason>". Always emits one of
    # the two so the caller's `[ "$status" = "FRESH" ]` check never sees an
    # empty string from a swallowed sha256sum failure.
    local fixture="$1"
    local golden="$2"
    local sha_file="$3"
    local version_file="$4"
    if [ ! -f "$fixture" ] || [ ! -f "$golden" ] || [ ! -f "$sha_file" ]; then
        echo "STALE: missing fixture/golden/sha for $fixture"
        return 0
    fi
    local sha_output
    if ! sha_output=$(sha256sum "$fixture" 2>/dev/null); then
        echo "STALE: sha256sum failed on $fixture (unreadable?)"
        return 0
    fi
    local current
    current=$(printf '%s' "$sha_output" | awk '{print $1}')
    if [ -z "$current" ]; then
        echo "STALE: empty sha256 for $fixture"
        return 0
    fi
    local recorded
    if ! recorded=$(cat "$sha_file" 2>/dev/null); then
        echo "STALE: cannot read $sha_file"
        return 0
    fi
    if [ "$current" != "$recorded" ]; then
        echo "STALE: $fixture SHA ($current) does not match recorded ($recorded)"
        return 0
    fi
    # SHA matched — soft-warn on FastTree version drift but stay FRESH so the
    # parity test still runs. A version mismatch is interesting (and usually
    # the cause when a previously-green parity test starts failing) but a
    # patch-level FastTree change rarely shifts topologies.
    if [ -f "$version_file" ] && [ -n "${FASTTREE_AVAILABLE:-}" ]; then
        local recorded_v
        recorded_v=$(cat "$version_file" 2>/dev/null)
        local current_v
        current_v=$(ft_get_version)
        if [ -n "$recorded_v" ] && [ -n "$current_v" ] && [ "$recorded_v" != "$current_v" ]; then
            echo "Warning: $fixture FastTree version drift: oracle generated with '$recorded_v', installed is '$current_v'; rerun with MIINT_FASTTREE_REGENERATE=1 if topology drifts" >&2
        fi
    fi
    echo "FRESH"
}

ft_regenerate_one "data/fasttree/tiny.fa"     "data/fasttree/tiny.golden.nwk"     "data/fasttree/tiny.golden.fixture.sha"     "data/fasttree/tiny.golden.fasttree.version"
ft_regenerate_one "data/fasttree/moderate.fa" "data/fasttree/moderate.golden.nwk" "data/fasttree/moderate.golden.fixture.sha" "data/fasttree/moderate.golden.fasttree.version"

ft_tiny_status=$(ft_check_one     "data/fasttree/tiny.fa"     "data/fasttree/tiny.golden.nwk"     "data/fasttree/tiny.golden.fixture.sha"     "data/fasttree/tiny.golden.fasttree.version")
ft_moderate_status=$(ft_check_one "data/fasttree/moderate.fa" "data/fasttree/moderate.golden.nwk" "data/fasttree/moderate.golden.fixture.sha" "data/fasttree/moderate.golden.fasttree.version")

if [ "$ft_tiny_status" = "FRESH" ]; then
    export MIINT_FASTTREE_TINY_PARITY_OK=1
else
    echo "Warning: tiny FastTree oracle: $ft_tiny_status; rerun with MIINT_FASTTREE_REGENERATE=1 to refresh"
fi
if [ "$ft_moderate_status" = "FRESH" ]; then
    export MIINT_FASTTREE_MODERATE_PARITY_OK=1
else
    echo "Warning: moderate FastTree oracle: $ft_moderate_status; rerun with MIINT_FASTTREE_REGENERATE=1 to refresh"
fi

# ASR (ancestral-state) parity goldens: independent ground-truth reconstructions
# (Brownian-motion GLS via the phylogenetic VCV; ape::ace for the discrete Mk models).
# The NUMERIC CSVs under data/asr/ ARE the fixed expected output -- COMMITTED, so they
# are always present and need no availability gate. The offline generator is a dev-only
# R + ape (GPL) tool deliberately kept out of this BSD tree
# (../duckdb-miint-localdocs/gen_asr_oracle.R); ape's code is never committed or
# distributed -- only its numeric output is.
#
# These previously sat behind a require-env MIINT_ASR_PARITY_OK gate driven by
# `sha256sum -c` against a data/asr/goldens.sha256 manifest. Both the gate and the
# manifest were removed for the same reason as the data/simsurvey/ ones below:
# `sha256sum -c` also fails on a MISMATCH, so a corrupted or edited golden SKIPPED the
# parity test and left CI green -- the exact opposite of the intended protection, and a
# Rule 10 (fail loud) violation. The parity tests themselves are the integrity check,
# and they now always run: a corrupted golden fails them, and a missing one fails the
# read_csv_auto that loads it.

# NOTE: the Kuczynski-2010 oracle bands, community_distances distance goldens and
# cluster_kmeans/cluster_upgma parity goldens under data/simsurvey/ are COMMITTED,
# so they are always present and need no availability gate. They previously sat
# behind sha256 gates; those were removed because `sha256sum -c` also fails on a
# MISMATCH, which turned an edited golden into a silently SKIPPED parity test --
# the opposite of the intended protection. The parity tests themselves are the
# integrity check, and they now always run.

# Procrustes parity goldens: independent numeric ground truth from SciPy
# (scipy.spatial.procrustes full case) + a NumPy port of the q2#338 partial
# technique, cross-checked against the shipped q2_diversity._partial_procrustes.
# The expected CSVs under data/procrustes/ are the committed, SHA-pinned output
# (data/procrustes/goldens.sha256); the generator (test/scripts/gen_procrustes_oracle.py)
# needs only SciPy/NumPy (BSD, in-tree-compatible). The gate below just verifies
# the committed goldens are intact before the parity test runs (require-env
# MIINT_PROCRUSTES_PARITY_OK). To refresh: rerun the generator under a SciPy env.
if [ -f data/procrustes/goldens.sha256 ] && (cd data/procrustes && sha256sum -c --quiet goldens.sha256) 2>/dev/null; then
    export MIINT_PROCRUSTES_PARITY_OK=1
else
    echo "Warning: procrustes parity goldens missing or corrupt; parity test skipped"
fi

# NCBI BLAST network reachability. Probes the BLAST CGI endpoint so
# live blast tests can skip gracefully in offline CI.
if curl -sSf --max-time 5 -o /dev/null \
        "https://blast.ncbi.nlm.nih.gov/blast/Blast.cgi" 2>/dev/null; then
    export BLAST_LIVE_AVAILABLE=1
fi

# ENA network reachability. Probes the Portal API with a cheap HEAD-ish call
# so tests that need live ENA access can skip gracefully in offline CI.
# Timeout is tight (3s) to avoid slowing down the common case.
if curl -sSf --max-time 3 -o /dev/null \
        "https://www.ebi.ac.uk/ena/portal/api/search?result=read_run&query=run_accession%3D%22ERR1074767%22&fields=run_accession&limit=1&format=tsv" \
        2>/dev/null; then
    export ENA_AVAILABLE=1
fi

# NCBI taxonomy dump reachability (opt-in integration test; the test downloads
# ~60MB). Cache into a contained repo dir (not the user's ~/.cache/miint) so the
# test is self-contained and re-runs hit the cache instead of re-downloading.
if curl -sSf --max-time 10 -I -o /dev/null \
        "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz" 2>/dev/null; then
    export MIINT_TAXDUMP_REMOTE=1
    export MIINT_TAXONOMY_CACHE_DIR="$PWD/data/cache/taxonomy"
    mkdir -p "$MIINT_TAXONOMY_CACHE_DIR"
fi

# ena_upload_reads streaming memory proof (opt-in, expensive). Uploads a
# multi-GB lazy view to file:// under a tight memory_limit; the streaming
# implementation completes in bounded memory whereas the old materialise-the-
# whole-relation path would OOM. Off by default (slow, multi-GB encode); run
# with `MIINT_ENA_BIG_STREAM_TEST=1 bash run_tests.sh` to include it.
if [ "${MIINT_ENA_BIG_STREAM_TEST:-0}" = "1" ]; then
    export MIINT_ENA_BIG_STREAM_TEST=1
fi

# ENA Webin V2 submission test endpoint. Live-integration tests for
# INSERT INTO ena.{projects,samples,...} require a real Webin account
# (free, registered at https://www.ebi.ac.uk/ena/submit/webin/). When the
# user provides credentials AND the dev/test server responds, we export
# ENA_WEBIN_TEST_AVAILABLE so guarded SQL tests can run.
if [ -n "$ENA_WEBIN_TEST_USER" ] && [ -n "$ENA_WEBIN_TEST_PASSWORD" ]; then
    export ENA_WEBIN_TEST_USER
    export ENA_WEBIN_TEST_PASSWORD
    if curl -sSf --max-time 3 -o /dev/null \
            "https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/swagger-ui/index.html" \
            2>/dev/null; then
        export ENA_WEBIN_TEST_AVAILABLE=1
    fi
fi

# ENA Webin V2 mock server. Provides canned XML receipts for INSERT INTO
# ena.{projects,samples,...} round-trip tests with no live credentials. The
# helper python script is in test/scripts/ena_webin_mock.py.
ENA_MOCK_PID=""
if [ -z "$ENA_WEBIN_MOCK_URL" ] && python3 -c "import http.server" 2>/dev/null; then
    python3 test/scripts/ena_webin_mock.py 0 > /tmp/ena_webin_mock.boot 2>&1 &
    ENA_MOCK_PID=$!
    # Inherit the existing trap (HTTP_SERVER_PID) and add the mock kill
    trap "kill $HTTP_SERVER_PID $ENA_MOCK_PID 2>/dev/null || true" EXIT
    for i in $(seq 1 25); do
        if [ -s /tmp/ena_webin_mock.boot ] && grep -q ENA_WEBIN_MOCK_URL /tmp/ena_webin_mock.boot; then
            export ENA_WEBIN_MOCK_URL="$(grep ENA_WEBIN_MOCK_URL /tmp/ena_webin_mock.boot | head -n1 | cut -d= -f2-)"
            break
        fi
        sleep 0.1
    done
    if [ -z "$ENA_WEBIN_MOCK_URL" ]; then
        echo "Warning: ENA Webin mock failed to start; submission round-trip tests will skip"
        kill $ENA_MOCK_PID 2>/dev/null || true
    else
        # Phase 8 Step 8a alias collision check: the operator sends an
        # authenticated GET to <portal_base>/search before each INSERT.
        # Point that base at the same mock so existing INSERT tests don't
        # try to reach the real EBI portal.
        export MIINT_ENA_PORTAL_URL_BASE="${ENA_WEBIN_MOCK_URL}/portal/api"
        # Phase 8 Step 8b checklist registry: the samples operator fetches
        # checklist XMLs to validate user attributes client-side. Point at
        # the mock for the same offline reasoning as the portal endpoint.
        export MIINT_ENA_CHECKLIST_URL_BASE="${ENA_WEBIN_MOCK_URL}/browser/api/xml"
        # L5 Reports API: the lifecycle table fns and DELETE-by-alias path
        # translate refname → accession via this base. Point at the mock so
        # SQL tests don't reach wwwdev.ebi.ac.uk.
        export MIINT_ENA_REPORTS_URL_BASE="${ENA_WEBIN_MOCK_URL}/submit/report"
    fi
fi

if conda run -n massql python3 -c "from massql import msql_engine" 2>/dev/null; then
    export MASSQL_PYTHON_AVAILABLE=1
fi

# Download and cache MassQL test data if not present
CACHE_DIR="data/cache"
mkdir -p "$CACHE_DIR"
MZML_FILE="$CACHE_DIR/bld_plt1_07_120_1.mzML"
EXPECTED_SHA="9be69d251cbf7d9b3c439ccc76dd65f055ddac96b946fc2f565e9a95bfd4ca46"

if [ ! -f "$MZML_FILE" ]; then
    echo "Downloading MassQL test data..."
    if ! wget -q -O "$MZML_FILE" "https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?forceDownload=true&file=f.MSV000085944/ccms_peak/raw_data/bld_plt1_07_120_1.mzML"; then
        rm -f "$MZML_FILE"
        echo "Warning: MassQL test data download failed, skipping MassQL tests"
    fi
fi
if echo "$EXPECTED_SHA  $MZML_FILE" | sha256sum -c --quiet 2>/dev/null; then
    export MASSQL_TEST_DATA="$MZML_FILE"
fi

# Download and cache GNPS test data if not present
GNPS_FILE="$CACHE_DIR/GNPS00002_A3_p.mzML"
if [ ! -f "$GNPS_FILE" ]; then
    echo "Downloading GNPS test data..."
    if ! wget -q -O "$GNPS_FILE" "https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?forceDownload=true&file=f.MSV000084494/ccms_peak/raw/GNPS00002_A3_p.mzML"; then
        rm -f "$GNPS_FILE"
        echo "Warning: GNPS test data download failed, skipping GNPS tests"
    fi
fi
if [ -f "$GNPS_FILE" ]; then
    export MASSQL_GNPS_DATA=1
fi

# Download and cache real mzXML test data if not present
MZXML_FILE="$CACHE_DIR/10125_P1_RA12_01_49.mzXML"
MZXML_EXPECTED_SHA="d026938157e5f640568c371ed6a0bca0de34e8c181da1443298671005e7ffe5a"
if [ ! -f "$MZXML_FILE" ]; then
    echo "Downloading mzXML test data..."
    if ! wget -q -O "$MZXML_FILE" "https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000080179%2Fccms_peak%2FmzXMLs%2F10125_P1_RA12_01_49.mzXML&forceDownload=true"; then
        rm -f "$MZXML_FILE"
        echo "Warning: mzXML test data download failed, skipping mzXML real data tests"
    fi
fi
if echo "$MZXML_EXPECTED_SHA  $MZXML_FILE" | sha256sum -c --quiet 2>/dev/null; then
    export MZXML_REAL_DATA="$MZXML_FILE"
fi

# Detect compile-time optional features by querying the built extension
if echo "SELECT * FROM miint_versions() WHERE library = 'HDF5';" | ./build/release/duckdb -csv 2>/dev/null | grep -q HDF5; then
    export HDF5_AVAILABLE=1
fi
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'detect_chimera_uchime';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export VSEARCH_AVAILABLE=1
fi
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'align_mafft';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export MAFFT_AVAILABLE=1
fi
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'align_abpoa';" | ./build/release/duckdb -csv 2>/dev/null | grep -q 1; then
    export ABPOA_AVAILABLE=1
fi
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'align_sortmerna_rrna';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export SORTMERNA_AVAILABLE=1
fi
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'unifrac_pcoa' AND function_type = 'table';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export UNIFRAC_AVAILABLE=1
fi
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'sylph_profile';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export SYLPH_AVAILABLE=1
fi
# libcurl streaming-upload transport (off on macOS — vsearch/OpenSSL symbol clash).
if echo "SELECT 1 FROM miint_versions() WHERE library = 'libcurl';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export MIINT_HAS_CURL=1
fi
# Compile-time gate (separate from runtime GPL_BOUNDARY_AVAILABLE which
# tracks whether the binary is on PATH). Set when the table function is
# registered — i.e., MIINT_HAS_GPL_BOUNDARY was on at build time.
if echo "SELECT 1 FROM duckdb_functions() WHERE function_name = 'phylogeny_fasttree' AND function_type = 'table';" | ./build/release/duckdb -csv -noheader 2>/dev/null | grep -q 1; then
    export PHYLOGENY_FASTTREE_AVAILABLE=1
fi

# Phase 5: real-data regression oracle.
#
# The BLAST-format output of `sortmerna 4.4.0 --blast '1 cigar qcov'` on the
# in-tree 100k-read environmental amplicons vs. gg_13_8_ref_set.fasta is
# checked in at data/sortmerna/real_oracle.blast.gz (1.9 MB gzipped). The
# submodule SHA that produced it is recorded alongside so we can detect when
# the oracle has gone stale.
#
# To regenerate after bumping ext/sortmerna: remove both files and rerun
# run_tests.sh with MIINT_SORTMERNA_REAL_DATA=1. That rebuilds the oracle
# using the submodule-built native CLI (the exact binary our library links),
# so the oracle and our embedded library always run the same version.
SMR_NATIVE_CLI="./build/release/extension/miint/sortmerna_build/src/sortmerna/sortmerna"
SMR_REAL_QUERY="ext/sortmerna/data/set2_environmental_study_550_amplicon.fasta"
SMR_REAL_REF="ext/sortmerna/data/gg_13_8_ref_set.fasta"
SMR_ORACLE_GZ="data/sortmerna/real_oracle.blast.gz"
SMR_ORACLE_SHA="data/sortmerna/real_oracle.submodule.sha"
SMR_SUBMODULE_HEAD=$(git -C ext/sortmerna rev-parse HEAD 2>/dev/null || echo "unknown")

if [ "${MIINT_SORTMERNA_REAL_DATA:-0}" = "1" ] && [ -x "$SMR_NATIVE_CLI" ] \
        && [ -f "$SMR_REAL_QUERY" ] && [ -f "$SMR_REAL_REF" ]; then
    echo "Regenerating sortmerna real-data oracle via native 4.4.0 CLI..."
    SMR_TMP=$(mktemp -d)
    if "$SMR_NATIVE_CLI" \
            --ref "$SMR_REAL_REF" --reads "$SMR_REAL_QUERY" \
            --workdir "$SMR_TMP" --aligned "$SMR_TMP/aligned" \
            --blast '1 cigar qcov' --num_alignments 1 --threads 4 > "$SMR_TMP/smr.log" 2>&1 \
            && [ -f "$SMR_TMP/aligned.blast" ]; then
        mkdir -p data/sortmerna
        gzip -c "$SMR_TMP/aligned.blast" > "$SMR_ORACLE_GZ"
        echo "$SMR_SUBMODULE_HEAD" > "$SMR_ORACLE_SHA"
        echo "Oracle regenerated at $SMR_ORACLE_GZ (submodule $SMR_SUBMODULE_HEAD)"
        rm -rf "$SMR_TMP"
    else
        # Preserve the CLI log for debugging — the tmpdir is about to go.
        SMR_FAIL_LOG="$(pwd)/smr_oracle_gen_fail.log"
        cp "$SMR_TMP/smr.log" "$SMR_FAIL_LOG" 2>/dev/null || true
        echo "Warning: sortmerna oracle generation failed; log saved to $SMR_FAIL_LOG"
        rm -rf "$SMR_TMP"
    fi
fi

# Export the oracle path only if both the gzipped file and its SHA record
# exist, AND the recorded SHA matches the current submodule HEAD. A mismatch
# means the submodule was bumped without regenerating — skip the test rather
# than silently validate against stale goldens.
if [ -f "$SMR_ORACLE_GZ" ] && [ -f "$SMR_ORACLE_SHA" ]; then
    SMR_RECORDED_SHA=$(cat "$SMR_ORACLE_SHA")
    if [ "$SMR_RECORDED_SHA" = "$SMR_SUBMODULE_HEAD" ]; then
        export SORTMERNA_REAL_ORACLE="$SMR_ORACLE_GZ"
    else
        echo "Warning: sortmerna oracle ($SMR_RECORDED_SHA) does not match submodule HEAD ($SMR_SUBMODULE_HEAD); skipping real-data test"
    fi
fi

make test
./build/release/extension/miint/tests

# read_fastx_fd_release.test must run under a low RLIMIT_NOFILE: it asserts that one scan
# over many paths holds descriptors proportional to thread count, not to path count, and
# a process with the usual limit cannot tell those two apart. `make test` above has no way
# to set a limit, so the file holds itself back with `require-env MIINT_LOW_FD_TEST` and
# runs here instead.
#
# Lowering the soft limit needs no privilege. If a hard limit already sits below the target
# we run anyway rather than skipping -- a tighter limit only makes the assertion stronger.
FD_RELEASE_TEST="test/sql/read_fastx_fd_release.test"
FD_RELEASE_LIMIT=256
echo "Running $FD_RELEASE_TEST with RLIMIT_NOFILE<=$FD_RELEASE_LIMIT..."
(
    ulimit -n "$FD_RELEASE_LIMIT" 2>/dev/null || true
    echo "  RLIMIT_NOFILE soft=$(ulimit -Sn) hard=$(ulimit -Hn)"
    # The || true above swallows the expected failure (hard limit already below target) along
    # with any unanticipated one. Since the soft limit can never exceed the hard limit, the
    # expected case always leaves us at or under the target -- so a soft limit still above it
    # here means the lower silently didn't take, and the test below would run with no real
    # descriptor pressure and pass without exercising anything.
    if [ "$(ulimit -Sn)" -gt "$FD_RELEASE_LIMIT" ]; then
        echo "  ERROR: RLIMIT_NOFILE is still $(ulimit -Sn), above the $FD_RELEASE_LIMIT target;" \
             "refusing to run $FD_RELEASE_TEST without real descriptor pressure" >&2
        exit 1
    fi
    MIINT_LOW_FD_TEST=1 ./build/release/test/unittest "$FD_RELEASE_TEST"
) || exit 1

# Run shell script tests
echo "Running shell script tests..."
for test_script in test/shell/*.sh; do
    if [ -f "$test_script" ]; then
        echo "Running $test_script..."
        if ! bash "$test_script"; then
            echo "Shell test failed: $test_script"
            exit 1
        fi
    fi
done
echo "All shell script tests passed!"
