// Structural verification of COPY FORMAT UBAM (issue #156). miint's own readers
// (read_sequences_sam / read_alignments) expose SEQ/QUAL/read_id/flags but NOT the
// @RG header, the absence of @SQ, or arbitrary per-read aux tags (zm) -- which are
// exactly the lima-load-bearing bits. The catch2 tests binary does not link
// libduckdb, so (like test_hfile_duckdb.cpp) this reads a committed golden uBAM
// with htslib and asserts its logical structure. The golden is produced by the
// writer and verified with `samtools view` at authoring; see
// test/sql/copy_ubam.test for the SEQ/QUAL/read_id round-trip and bind-error cases.
//
// Golden generated by (mirror of the copy_ubam.test happy path, plus a NULL-tag row):
//   COPY (SELECT * FROM (VALUES
//     ('movie/1/ccs','ACGTACGT',[30,31,32,33,34,35,36,37]::UTINYINT[],1001),
//     ('movie/2/ccs','TTTTGGGG',[20,20,20,20,25,25,25,25]::UTINYINT[],1002),
//     ('movie/3/ccs','CCCCAAAA',[40,40,40,40,10,10,10,10]::UTINYINT[],NULL::INTEGER))
//     AS t(read_id,sequence1,qual1,zmw))
//   TO 'data/sam/ubam_ccs_golden.bam'
//   (FORMAT UBAM, READ_GROUP {ID:'qiita', PL:'PACBIO', DS:'READTYPE=CCS'}, TAGS {zm: zmw});

#include <catch2/catch_test_macros.hpp>

#include <htslib-1.22.1/htslib/hts.h>
#include <htslib-1.22.1/htslib/kstring.h>
#include <htslib-1.22.1/htslib/sam.h>

#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace {

struct RecordView {
	uint16_t flag = 0;
	std::string seq;
	std::vector<uint8_t> qual;
	bool has_zm = false;
	int64_t zm = 0;
	bool has_rg = false;
	std::string rg;
};

// Decode a BAM into a qname->record map so assertions don't depend on write order.
std::map<std::string, RecordView> ReadBam(const std::string &path, sam_hdr_t **out_hdr) {
	samFile *fp = sam_open(path.c_str(), "rb");
	REQUIRE(fp != nullptr);
	sam_hdr_t *hdr = sam_hdr_read(fp);
	REQUIRE(hdr != nullptr);

	std::map<std::string, RecordView> out;
	bam1_t *aln = bam_init1();
	while (sam_read1(fp, hdr, aln) >= 0) {
		RecordView rv;
		rv.flag = aln->core.flag;
		const uint8_t *seq = bam_get_seq(aln);
		for (int i = 0; i < aln->core.l_qseq; i++) {
			rv.seq += seq_nt16_str[bam_seqi(seq, i)];
		}
		const uint8_t *q = bam_get_qual(aln);
		for (int i = 0; i < aln->core.l_qseq; i++) {
			rv.qual.push_back(q[i]);
		}
		if (uint8_t *zm = bam_aux_get(aln, "zm")) {
			rv.has_zm = true;
			rv.zm = bam_aux2i(zm);
		}
		if (uint8_t *rg = bam_aux_get(aln, "RG")) {
			rv.has_rg = true;
			rv.rg = bam_aux2Z(rg);
		}
		out[std::string(bam_get_qname(aln))] = std::move(rv);
	}
	bam_destroy1(aln);
	sam_close(fp);
	*out_hdr = hdr; // caller destroys
	return out;
}

const std::string GOLDEN = "data/sam/ubam_ccs_golden.bam";

} // namespace

TEST_CASE("COPY FORMAT UBAM golden: headerless BAM, no @SQ, one settable @RG", "[copy][ubam]") {
	sam_hdr_t *hdr = nullptr;
	auto recs = ReadBam(GOLDEN, &hdr);

	// No @SQ lines: these reads are unaligned, no reference dictionary.
	CHECK(hdr->n_targets == 0);
	CHECK(sam_hdr_count_lines(hdr, "SQ") == 0);

	// Exactly one @RG carrying the settable DS (the field lima keys on) + PL.
	REQUIRE(sam_hdr_count_lines(hdr, "RG") == 1);
	kstring_t ks = KS_INITIALIZE;
	REQUIRE(sam_hdr_find_tag_id(hdr, "RG", NULL, NULL, "ID", &ks) == 0);
	CHECK(std::string(ks.s) == "qiita");
	ks.l = 0;
	REQUIRE(sam_hdr_find_tag_id(hdr, "RG", NULL, NULL, "DS", &ks) == 0);
	CHECK(std::string(ks.s) == "READTYPE=CCS");
	ks.l = 0;
	REQUIRE(sam_hdr_find_tag_id(hdr, "RG", NULL, NULL, "PL", &ks) == 0);
	CHECK(std::string(ks.s) == "PACBIO");
	ks_free(&ks);
	sam_hdr_destroy(hdr);
}

TEST_CASE("COPY FORMAT UBAM golden: per-record SEQ/QUAL, flag=4, RG:Z and zm:i", "[copy][ubam]") {
	sam_hdr_t *hdr = nullptr;
	auto recs = ReadBam(GOLDEN, &hdr);
	sam_hdr_destroy(hdr);

	REQUIRE(recs.size() == 3);

	const auto &r1 = recs.at("movie/1/ccs");
	CHECK((r1.flag & BAM_FUNMAP) != 0);
	CHECK(r1.seq == "ACGTACGT");
	CHECK(r1.qual == std::vector<uint8_t>({30, 31, 32, 33, 34, 35, 36, 37}));
	CHECK(r1.has_zm);
	CHECK(r1.zm == 1001);
	CHECK(r1.has_rg);
	CHECK(r1.rg == "qiita");

	const auto &r2 = recs.at("movie/2/ccs");
	CHECK((r2.flag & BAM_FUNMAP) != 0);
	CHECK(r2.seq == "TTTTGGGG");
	CHECK(r2.qual == std::vector<uint8_t>({20, 20, 20, 20, 25, 25, 25, 25}));
	CHECK(r2.zm == 1002);
	CHECK(r2.rg == "qiita");

	// r3's zmw was NULL -> no zm tag on that record, but SEQ/QUAL/RG still present.
	const auto &r3 = recs.at("movie/3/ccs");
	CHECK((r3.flag & BAM_FUNMAP) != 0);
	CHECK(r3.seq == "CCCCAAAA");
	CHECK_FALSE(r3.has_zm);
	CHECK(r3.rg == "qiita");
}
